-- System Audit Logs Table
create table if not exists system_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users, -- The person who performed the action
  action_type text not null, -- 'CREATE_EMPLOYEE', 'CREDIT_SALARY', 'REBOOT_ROUTER', etc.
  entity_type text, -- 'employee', 'router', 'client'
  entity_id text, -- ID of the affected item
  details jsonb, -- JSON blob for metadata
  ip_address text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table system_logs enable row level security;

-- Only admins can view logs
create policy "Admins can view logs" on system_logs for select using (
  exists (select 1 from profiles where id = auth.uid() and role = 'admin')
);

-- Re-enable RLS on core tables
alter table profiles enable row level security;
alter table employees enable row level security;

-- Strict Profile Policies
drop policy if exists "Public profiles are viewable by everyone." on profiles;
create policy "Users can view their own profile" on profiles for select using (auth.uid() = id);
create policy "Admins can view all profiles" on profiles for select using (
  exists (select 1 from profiles where id = auth.uid() and role = 'admin')
);
create policy "Admins can update all profiles" on profiles for update using (
  exists (select 1 from profiles where id = auth.uid() and role = 'admin')
);

-- Strict Employee Policies
drop policy if exists "Employees can view their own data" on employees;
create policy "Employees can view their own data" on employees for select using (auth.uid() = id);
create policy "Admins can manage employees" on employees for all using (
  exists (select 1 from profiles where id = auth.uid() and role = 'admin')
);
