-- Add role to profiles
alter table profiles add column if not exists role text default 'client';

-- Table for employee-specific data
create table if not exists employees (
  id uuid references auth.users not null primary key,
  base_salary decimal(12, 2) default 0.00,
  current_balance decimal(12, 2) default 0.00,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Table for client assignments
create table if not exists employee_clients (
  id bigint generated by default as identity primary key,
  employee_id uuid references auth.users not null,
  client_id uuid references auth.users not null,
  assigned_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(employee_id, client_id)
);

-- Table for payroll transactions
create table if not exists payroll_history (
  id bigint generated by default as identity primary key,
  employee_id uuid references auth.users not null,
  amount decimal(12, 2) not null,
  type text not null, -- 'salary_credit', 'withdrawal', 'bonus'
  status text default 'completed', -- 'completed', 'pending', 'cancelled'
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Table for withdrawal requests
create table if not exists withdrawal_requests (
  id bigint generated by default as identity primary key,
  employee_id uuid references auth.users not null,
  amount decimal(12, 2) not null,
  status text default 'pending', -- 'pending', 'approved', 'rejected'
  admin_notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  processed_at timestamp with time zone
);

-- RLS Policies
alter table employees enable row level security;
alter table employee_clients enable row level security;
alter table payroll_history enable row level security;
alter table withdrawal_requests enable row level security;

-- Policies for employees (can view their own data)
create policy "Employees can view their own data" on employees for select using (auth.uid() = id);
create policy "Employees can view their client assignments" on employee_clients for select using (auth.uid() = employee_id);
create policy "Employees can view their payroll history" on payroll_history for select using (auth.uid() = employee_id);
create policy "Employees can view their withdrawal requests" on withdrawal_requests for select using (auth.uid() = employee_id);
create policy "Employees can create withdrawal requests" on withdrawal_requests for insert with check (auth.uid() = employee_id);

-- Admin policies (can view and manage everything)
create policy "Admins can manage employees" on employees for all using (
  exists (select 1 from profiles where id = auth.uid() and role = 'admin')
);

create policy "Admins can manage client assignments" on employee_clients for all using (
  exists (select 1 from profiles where id = auth.uid() and role = 'admin')
);

create policy "Admins can manage payroll history" on payroll_history for all using (
  exists (select 1 from profiles where id = auth.uid() and role = 'admin')
);

create policy "Admins can manage withdrawal requests" on withdrawal_requests for all using (
  exists (select 1 from profiles where id = auth.uid() and role = 'admin')
);
