-- Create a table for M-Pesa transactions if it doesn't exist
create table if not exists mpesa_transactions (
  id bigint generated by default as identity primary key,
  phone_number text not null,
  amount int not null,
  checkout_request_id text unique not null,
  merchant_request_id text not null,
  mpesa_receipt_number text,
  result_desc text,
  status text default 'PENDING', -- PENDING, COMPLETED, FAILED
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table mpesa_transactions enable row level security;

-- Policies
-- Drop existing policy if it exists to avoid errors when re-running
drop policy if exists "Service role can do everything on mpesa_transactions" on mpesa_transactions;

-- Allow the service role (backend) to do everything
create policy "Service role can do everything on mpesa_transactions"
  on mpesa_transactions
  using ( auth.role() = 'service_role' )
  with check ( auth.role() = 'service_role' );
