-- Notifications table for employee alerts
create table if not exists employee_notifications (
  id bigint generated by default as identity primary key,
  employee_id uuid references auth.users not null,
  title text not null,
  body text not null,
  type text default 'info', -- 'client_assigned', 'salary_credit', 'withdrawal_approved', 'withdrawal_rejected', 'info'
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table employee_notifications enable row level security;

-- Employees can only read their own notifications
create policy "Employees can view own notifications" on employee_notifications for select using (auth.uid() = employee_id);
create policy "Employees can update own notifications" on employee_notifications for update using (auth.uid() = employee_id);

-- Admins can insert notifications (via service role, so no policy needed for insert)
-- But allow service_role through
create policy "Service role can insert notifications" on employee_notifications for insert with check (true);
