-- Create a table for public profiles using Supabase Auth
create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,
  website text,

  constraint username_length check (char_length(username) >= 3)
);

-- Set up Row Level Security (RLS)
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- MikroTik Routers Table
create table mikrotik_routers (
  id bigint generated by default as identity primary key,
  name text not null,
  host text not null,
  port int default 8728,
  username text not null,
  password text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table mikrotik_routers enable row level security;

-- Only authenticated users can view/add routers (Restrict this further in prod)
create policy "Authenticated users can view routers."
  on mikrotik_routers for select
  using ( auth.role() = 'authenticated' );

create policy "Authenticated users can insert routers."
  on mikrotik_routers for insert
  with check ( auth.role() = 'authenticated' );

-- SmartOLT Devices Table
create table smartolt_devices (
  id bigint generated by default as identity primary key,
  name text not null,
  api_key text not null,
  url text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table smartolt_devices enable row level security;

-- Same RLS for SmartOLT
create policy "Authenticated users can view smartolt devices."
  on smartolt_devices for select
  using ( auth.role() = 'authenticated' );

create policy "Authenticated users can insert smartolt devices."
  on smartolt_devices for insert
  with check ( auth.role() = 'authenticated' );
