-- Support Tickets Table
create table if not exists support_tickets (
  id bigint generated by default as identity primary key,
  client_id uuid references auth.users not null,
  subject text not null,
  description text not null,
  priority text default 'medium', -- 'low', 'medium', 'high', 'urgent'
  status text default 'open', -- 'open', 'assigned', 'resolved', 'closed'
  assigned_employee_id uuid references auth.users,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  resolved_at timestamp with time zone,
  admin_notes text
);

alter table support_tickets enable row level security;

-- Clients can view and create their own tickets
create policy "Clients can manage own tickets" on support_tickets for all using (auth.uid() = client_id);

-- Employees can view tickets assigned to them
create policy "Employees can view assigned tickets" on support_tickets for select using (auth.uid() = assigned_employee_id);

-- Admins can manage all tickets
create policy "Admins can manage all tickets" on support_tickets for all using (
  exists (select 1 from profiles where id = auth.uid() and role = 'admin')
);

-- Update profiles to include location for "nearest employee" logic later
alter table profiles add column if not exists last_location_lat decimal(10, 8);
alter table profiles add column if not exists last_location_lng decimal(11, 8);
